import fs from 'fs';
import path from 'path';

// Parse .env file manually to load env variables for database connectivity BEFORE importing Prisma
const envPath = path.resolve(process.cwd(), '.env');
if (fs.existsSync(envPath)) {
  const envContent = fs.readFileSync(envPath, 'utf8');
  for (const line of envContent.split('\n')) {
    const trimmed = line.trim();
    if (trimmed && !trimmed.startsWith('#')) {
      const [key, ...values] = trimmed.split('=');
      const val = values.join('=').replace(/^['"]|['"]$/g, '');
      process.env[key.trim()] = val.trim();
    }
  }
}

import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient, ListingStatus, ListingFor, PropertyType, Furnishing, Possession, Ownership, Parking } from '@prisma/client';

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const OWNER_ID = 'd8bf34a5-12a8-4bb9-a35c-7f89b9dcd872';

const IMAGES = [
  'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
  'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
];

const PROPERTIES_TO_SEED = [
  // --- GHAZIABAD ---
  {
    city: 'Ghaziabad',
    locality: 'Indirapuram',
    title: 'Modern 2BHK in Indirapuram',
    description: 'Fully semi-furnished 2BHK apartment in high-rise gated society. Complete woodwork and modular kitchen done. 24/7 security and lift access.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 15000,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 1100,
    pinCode: '201014',
    fullAddress: 'C-402, Shipra Riviera, Indirapuram, Ghaziabad, UP',
  },
  {
    city: 'Ghaziabad',
    locality: 'Vasundhara',
    title: 'Premium 3BHK Flat in Vasundhara',
    description: 'Ready to move 3BHK flat located in the prime sector of Vasundhara. Walking distance to Metro Station. Dedicated car parking and power backup.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 7500000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1600,
    pinCode: '201012',
    fullAddress: 'Plot 45, Sector 5, Vasundhara, Ghaziabad, UP',
  },
  {
    city: 'Ghaziabad',
    locality: 'Vaishali',
    title: 'Luxurious 4BHK Villa in Vaishali',
    description: 'Ultra luxury independent villa with private lawn, modern modular kitchen, luxury flooring, and built-in wardrobes. Fully secured gated area.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.VILLA,
    price: 21000000,
    bedrooms: 4,
    bathrooms: 4,
    carpetArea: 3200,
    pinCode: '201010',
    fullAddress: 'Sector 3, Vaishali, Ghaziabad, UP',
  },
  {
    city: 'Ghaziabad',
    locality: 'Raj Nagar Extension',
    title: 'Spacious 3BHK in Raj Nagar Extension',
    description: 'Breathtaking park facing 3BHK in a premium society. Modular kitchen, high-speed elevators, swimming pool, club house, and kids play zone.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 18000,
    bedrooms: 3,
    bathrooms: 2,
    carpetArea: 1450,
    pinCode: '201017',
    fullAddress: 'Tower B, KW Srishti, Raj Nagar Extension, Ghaziabad, UP',
  },
  {
    city: 'Ghaziabad',
    locality: 'Vaishali',
    title: 'Cozy 1BHK Studio near Metro Station',
    description: 'Ideal studio apartment for single professionals or couples. Within 500m of Vaishali Metro Station. Power backup and water supply included.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.STUDIO,
    price: 10000,
    bedrooms: 1,
    bathrooms: 1,
    carpetArea: 550,
    pinCode: '201010',
    fullAddress: 'A-12, Sector 1, Vaishali, Ghaziabad, UP',
  },
  {
    city: 'Ghaziabad',
    locality: 'Crossings Republik',
    title: 'Highrise 2BHK with Balcony in Crossings',
    description: 'Excellent layout with double balconies offering panoramic views of the city. Round-the-clock water supply and piped gas connectivity.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 5500000,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 1050,
    pinCode: '201016',
    fullAddress: '12th Floor, GH-07, Crossings Republik, Ghaziabad, UP',
  },
  {
    city: 'Ghaziabad',
    locality: 'Kavi Nagar',
    title: 'Independent 3BHK House in Kavi Nagar',
    description: 'Single-storey independent house on a wide road. Friendly residential locality, close to markets, schools, and hospitals.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.HOUSE,
    price: 18000000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 2100,
    pinCode: '201002',
    fullAddress: 'KB-88, Kavi Nagar, Ghaziabad, UP',
  },
  {
    city: 'Ghaziabad',
    locality: 'Indirapuram',
    title: 'Skyline 4BHK Penthouse in Indirapuram',
    description: 'Super premium penthouse with terrace access, designer interiors, and premium bathroom fittings. Direct access to clubhouse amenities.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.PENTHOUSE,
    price: 32000000,
    bedrooms: 4,
    bathrooms: 4,
    carpetArea: 4200,
    pinCode: '201014',
    fullAddress: 'Tower Skyline, Orange County, Indirapuram, Ghaziabad, UP',
  },
  {
    city: 'Ghaziabad',
    locality: 'Vaishali Sector 4',
    title: 'Semi-furnished 2BHK in Vaishali Sector 4',
    description: 'Spacious drawing room, modular kitchen, and double balconies. Low maintenance charges. Gated community with 24h guards.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 16500,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 1150,
    pinCode: '201010',
    fullAddress: 'Plot 232, Vaishali Sector 4, Ghaziabad, UP',
  },
  {
    city: 'Ghaziabad',
    locality: 'Wave City',
    title: 'Under-construction 3BHK in Wave City',
    description: 'Early bird offer! Booking open for modern 3BHK flat on NH-24. High appreciation value, luxury amenities, green area.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 6500000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1500,
    pinCode: '201015',
    fullAddress: 'Wave City, Sector 2, NH-24, Ghaziabad, UP',
  },

  // --- PUNE ---
  {
    city: 'Pune',
    locality: 'Koregaon Park',
    title: 'Elegant 3BHK Flat in Koregaon Park',
    description: 'A premium green living experience in Pune\'s most sought after neighborhood. Modern amenities, modular kitchen, and private parking slots.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 45000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1750,
    pinCode: '411001',
    fullAddress: 'Lane 5, Koregaon Park, Pune, Maharashtra',
  },
  {
    city: 'Pune',
    locality: 'Hinjewadi',
    title: 'Luxurious 2BHK in Hinjewadi Phase 1',
    description: 'Perfect home for IT professionals. Safe and secure gated society with gym, pool, and community center. Walkable distance to major tech parks.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 8500000,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 1100,
    pinCode: '411057',
    fullAddress: 'Phase 1, Hinjewadi, Pune, Maharashtra',
  },
  {
    city: 'Pune',
    locality: 'Kothrud',
    title: 'Premium 4BHK Villa in Kothrud',
    description: 'Stunning independent villa with private garden, high-end wood finishes, and smart home automation features. Highly prime area.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.VILLA,
    price: 34000000,
    bedrooms: 4,
    bathrooms: 4,
    carpetArea: 3600,
    pinCode: '411038',
    fullAddress: 'Ideal Colony, Kothrud, Pune, Maharashtra',
  },
  {
    city: 'Pune',
    locality: 'Viman Nagar',
    title: 'Furnished 1BHK in Viman Nagar',
    description: 'Fully furnished 1BHK apartment ideal for students or working singles. Near Phoenix Mall and Airport. Double bed, AC, and sofa included.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 22000,
    bedrooms: 1,
    bathrooms: 1,
    carpetArea: 650,
    pinCode: '411014',
    fullAddress: 'Dutt Mandir Road, Viman Nagar, Pune, Maharashtra',
  },
  {
    city: 'Pune',
    locality: 'Wakad',
    title: 'Spacious 3BHK Flat in Wakad',
    description: 'Superb ventilation and natural light. Society has fully functional club house, sports court, and children\'s playing grid.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 11500000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1550,
    pinCode: '411057',
    fullAddress: 'Choudhary Park, Wakad, Pune, Maharashtra',
  },
  {
    city: 'Pune',
    locality: 'Baner',
    title: 'Modern 2BHK Flat in Baner',
    description: 'Located in a highly vibrant neighborhood with upscale cafes and shopping outlets. Modular kitchen, gas pipeline, and dedicated power.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 28000,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 1200,
    pinCode: '411045',
    fullAddress: 'Baner Road, Baner, Pune, Maharashtra',
  },
  {
    city: 'Pune',
    locality: 'Kalyani Nagar',
    title: 'Sleek 4BHK Penthouse in Kalyani Nagar',
    description: 'Luxurious duplex penthouse with expansive views of Pune skyline. Top-end kitchen, private terrace deck, and 3 reserved parking spaces.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.PENTHOUSE,
    price: 48000000,
    bedrooms: 4,
    bathrooms: 4,
    carpetArea: 4500,
    pinCode: '411006',
    fullAddress: 'Kalyani Nagar, Pune, Maharashtra',
  },
  {
    city: 'Pune',
    locality: 'Hadapsar',
    title: 'Cozy 2BHK Flat in Hadapsar',
    description: 'Conveniently situated near Magarpatta City. Perfect layout with double bathrooms and modern utility fittings.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 7200000,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 1000,
    pinCode: '411028',
    fullAddress: 'Solapur Road, Hadapsar, Pune, Maharashtra',
  },
  {
    city: 'Pune',
    locality: 'Aundh',
    title: 'Independent Duplex House in Aundh',
    description: 'Modern duplex with high ceilings, private driveway, and quiet leafy surroundings. Highly accessible to University road.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.HOUSE,
    price: 26000000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 2400,
    pinCode: '411007',
    fullAddress: 'DP Road, Aundh, Pune, Maharashtra',
  },
  {
    city: 'Pune',
    locality: 'Kharadi',
    title: 'Premium 3BHK Flat in Kharadi',
    description: 'Close to EON IT Park. High rise unit with modern architecture, premium vitrified tiles, and direct access to swimming pool.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 38000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1600,
    pinCode: '411014',
    fullAddress: 'Kharadi Bypass Road, Kharadi, Pune, Maharashtra',
  },

  // --- MUMBAI ---
  {
    city: 'Mumbai',
    locality: 'Bandra West',
    title: 'Sea-facing 3BHK in Bandra West',
    description: 'Breathtaking direct sea views from the living room and master bedroom. Designer luxury interiors with high-end appliances and private lobby.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 210000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1800,
    pinCode: '400050',
    fullAddress: 'Carter Road, Bandra West, Mumbai, Maharashtra',
  },
  {
    city: 'Mumbai',
    locality: 'Worli',
    title: 'Ultra-luxury 4BHK flat in Worli Skyline',
    description: 'Located in a prestigious high-rise with premium amenities including private theater, sky lounge, and olympic-size swimming pool.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 85000000,
    bedrooms: 4,
    bathrooms: 4,
    carpetArea: 3200,
    pinCode: '400018',
    fullAddress: 'Worli Sea Face, Worli, Mumbai, Maharashtra',
  },
  {
    city: 'Mumbai',
    locality: 'Andheri West',
    title: 'Sleek 2BHK Flat in Andheri West',
    description: 'Centrally located flat near Lokhandwala market. Semi-furnished with modern modular cabinets, clean marble flooring, and gas line.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 65000,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 950,
    pinCode: '400053',
    fullAddress: 'Link Road, Andheri West, Mumbai, Maharashtra',
  },
  {
    city: 'Mumbai',
    locality: 'Powai',
    title: 'Cozy 1BHK Studio in Powai Hiranandani',
    description: 'Premium European style studio flat with high-end furnishings, double windows, air conditioning, and integrated home systems.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.STUDIO,
    price: 40000,
    bedrooms: 1,
    bathrooms: 1,
    carpetArea: 550,
    pinCode: '400076',
    fullAddress: 'Central Avenue, Hiranandani Gardens, Powai, Mumbai, Maharashtra',
  },
  {
    city: 'Mumbai',
    locality: 'Powai',
    title: 'Premium 3BHK Flat in Powai',
    description: 'Excellent layout with lake view. Highly secure gated complex with full club house, gym, tennis court, and basement parking.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 29000000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1450,
    pinCode: '400076',
    fullAddress: 'Lake Boulevard Road, Powai, Mumbai, Maharashtra',
  },
  {
    city: 'Mumbai',
    locality: 'Worli',
    title: 'Luxury 2BHK Flat in Lower Parel',
    description: 'Modern luxury flat in corporate hub area. Walking distance to premium offices. Air conditioned rooms and modular kitchen.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 32000000,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 1100,
    pinCode: '400013',
    fullAddress: 'Senapati Bapat Marg, Lower Parel, Mumbai, Maharashtra',
  },
  {
    city: 'Mumbai',
    locality: 'Worli',
    title: 'Exclusive 5BHK Penthouse in Malabar Hill',
    description: 'Top floor exclusive home with private terrace pool, direct 360-degree ocean views, premium security systems, and helper quarters.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.PENTHOUSE,
    price: 240000000,
    bedrooms: 5,
    bathrooms: 5,
    carpetArea: 6500,
    pinCode: '400006',
    fullAddress: 'Ridge Road, Malabar Hill, Mumbai, Maharashtra',
  },
  {
    city: 'Mumbai',
    locality: 'Powai',
    title: 'High-rise 2BHK Flat in Goregaon East',
    description: 'Located next to Aarey Colony offering fresh air and greenery. High-speed elevators, fully secure perimeter, and reserved parking space.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 50000,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 1050,
    pinCode: '400063',
    fullAddress: 'Western Express Highway, Goregaon East, Mumbai, Maharashtra',
  },
  {
    city: 'Mumbai',
    locality: 'Powai',
    title: 'Premium 3BHK Flat in Chembur',
    description: 'Excellent connectivity to Eastern Freeway. Highly spacious rooms, modular kitchen cabinets, and premium wood tiling in master suite.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 22000000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1350,
    pinCode: '400071',
    fullAddress: 'Sion-Trombay Road, Chembur, Mumbai, Maharashtra',
  },
  {
    city: 'Mumbai',
    locality: 'Bandra West',
    title: 'Elegant 1BHK Flat in Juhu',
    description: 'Quiet, premium residential road near the beach. Air conditioning, geysers, modular wardrobes, and secure entry.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 45000,
    bedrooms: 1,
    bathrooms: 1,
    carpetArea: 600,
    pinCode: '400049',
    fullAddress: 'Juhu Tara Road, Juhu, Mumbai, Maharashtra',
  },

  // --- DELHI / DELHI NCR ---
  {
    city: 'Delhi NCR',
    locality: 'Connaught Place',
    title: 'Premium 3BHK Builder Floor in GK 2',
    description: 'High-end independent builder floor with lift and gated stilt parking. Modern Italian marble, modular kitchen, and double balconies.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 37500000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 2200,
    pinCode: '110048',
    fullAddress: 'M-Block, Greater Kailash 2, New Delhi',
  },
  {
    city: 'Delhi NCR',
    locality: 'Dwarka',
    title: 'Modern 3BHK Flat in Dwarka Sector 12',
    description: 'Spacious park facing DDA SFS flat with modular fittings, power backup, and gated round-the-clock guards. Close to metro station.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 35000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1650,
    pinCode: '110075',
    fullAddress: 'Pocket 3, Sector 12, Dwarka, New Delhi',
  },
  {
    city: 'Delhi NCR',
    locality: 'Connaught Place',
    title: 'Luxurious 5BHK Bungalow in Vasant Vihar',
    description: 'Exquisite independent bungalow in diplomatic area. Private sprawling lawns, servant rooms, premium designer architecture.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.VILLA,
    price: 180000000,
    bedrooms: 5,
    bathrooms: 5,
    carpetArea: 5800,
    pinCode: '110057',
    fullAddress: 'Poorvi Marg, Vasant Vihar, New Delhi',
  },
  {
    city: 'Delhi NCR',
    locality: 'Connaught Place',
    title: 'Spacious 2BHK Builder Floor in Lajpat Nagar',
    description: 'Superb location in South Delhi near central market. Semi-furnished floor, modular kitchen, clean baths, split AC installations.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 28000,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 1100,
    pinCode: '110024',
    fullAddress: 'K-Block, Lajpat Nagar II, New Delhi',
  },
  {
    city: 'Delhi NCR',
    locality: 'Sector 62, Noida',
    title: 'Highrise 3BHK Flat in Sector 62, Noida',
    description: 'High-end layout inside a premium residential society. Walking distance to Metro station. Modular woodwork, pool, and club access.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 13500000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1750,
    pinCode: '201301',
    fullAddress: 'Stellar Park, Sector 62, Noida, UP',
  },
  {
    city: 'Delhi NCR',
    locality: 'Connaught Place',
    title: 'Luxury 4BHK Floor in Defence Colony',
    description: 'Fully air conditioned builder floor with private lift lobby, modular kitchen, server rooms, and premium wood floorings.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 150000,
    bedrooms: 4,
    bathrooms: 4,
    carpetArea: 2800,
    pinCode: '110024',
    fullAddress: 'A-Block, Defence Colony, New Delhi',
  },
  {
    city: 'Delhi NCR',
    locality: 'Dwarka',
    title: 'Sleek 2BHK Flat in Dwarka Sector 22',
    description: 'Ready to move flat inside luxury cooperative group housing. Covered car parking, modular kitchen, and double balconies.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 9500000,
    bedrooms: 2,
    bathrooms: 2,
    carpetArea: 1200,
    pinCode: '110077',
    fullAddress: 'Sector 22, Dwarka, New Delhi',
  },
  {
    city: 'Delhi NCR',
    locality: 'Connaught Place',
    title: 'Furnished 1BHK Flat in Saket',
    description: 'Cozy and quiet flat ideal for professionals. Walking distance to Saket Metro and Select Citywalk. Full security, TV, bed, fridge, and AC.',
    listingFor: ListingFor.RENT,
    propertyType: PropertyType.APARTMENT,
    price: 20000,
    bedrooms: 1,
    bathrooms: 1,
    carpetArea: 600,
    pinCode: '110017',
    fullAddress: 'J-Block, Saket, New Delhi',
  },
  {
    city: 'Delhi NCR',
    locality: 'Sector 62, Noida',
    title: 'Premium 4BHK Villa in Sector 150, Noida',
    description: 'Modern luxury smart villa in Noida\'s greenest sector. Private garden area, club house access, prime design layout.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.VILLA,
    price: 34000000,
    bedrooms: 4,
    bathrooms: 4,
    carpetArea: 3500,
    pinCode: '201310',
    fullAddress: 'Sector 150, Noida, UP',
  },
  {
    city: 'Delhi NCR',
    locality: 'DLF Phase 3, Gurgaon',
    title: 'Modern 3BHK Flat in DLF Phase 3, Gurgaon',
    description: 'Close to Cyber City. Architecturally designed builder floor with gated parking, marble flooring, and modular kitchen systems.',
    listingFor: ListingFor.SALE,
    propertyType: PropertyType.APARTMENT,
    price: 21000000,
    bedrooms: 3,
    bathrooms: 3,
    carpetArea: 1950,
    pinCode: '122002',
    fullAddress: 'U-Block, DLF Phase 3, Gurugram, Haryana',
  },
];

async function seed() {
  console.log('🏁 Starting Properties Seeding script...');

  // Ensure owner profile exists
  console.log(`Checking/Creating Owner Profile: ${OWNER_ID}`);
  await prisma.profile.upsert({
    where: { id: OWNER_ID },
    update: {
      phoneVerified: true,
      role: 'USER',
    },
    create: {
      id: OWNER_ID,
      name: 'Sample Real Estate Owner',
      email: 'owner@example.com',
      phone: '9876543210',
      phoneVerified: true,
      role: 'USER',
    },
  });

  console.log('Seeding 40 sample properties...');
  let seededCount = 0;

  for (let i = 0; i < PROPERTIES_TO_SEED.length; i++) {
    const prop = PROPERTIES_TO_SEED[i];
    const imageUrl = IMAGES[i % IMAGES.length];

    const listing = await prisma.listing.create({
      data: {
        ownerId: OWNER_ID,
        listingFor: prop.listingFor,
        propertyType: prop.propertyType,
        title: prop.title,
        description: prop.description,
        city: prop.city,
        locality: prop.locality,
        pinCode: prop.pinCode,
        fullAddress: prop.fullAddress,
        askingPrice: prop.price,
        status: ListingStatus.ACTIVE,
        isFeatured: i % 3 === 0,
        bedrooms: prop.bedrooms,
        bathrooms: prop.bathrooms,
        carpetArea: prop.carpetArea,
        keyHighlights: ['Direct Owner', 'Verified Listing', 'Zero Brokerage'],
      },
    });

    await prisma.listingImage.create({
      data: {
        listingId: listing.id,
        imageUrl: imageUrl,
        isPrimary: true,
        displayOrder: 0,
      },
    });

    seededCount++;
  }

  console.log(`✨ Successfully seeded ${seededCount} properties into the database!`);
}

seed()
  .then(async () => {
    await prisma.$disconnect();
    process.exit(0);
  })
  .catch(async (err) => {
    console.error('❌ Seeding failed with error:', err);
    await prisma.$disconnect();
    process.exit(1);
  });
